# Generated by Django 6.0.1 on 2026-01-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('birthday', models.DateField()),
                ('access_req', models.SmallIntegerField(default=0)),
                ('color', models.CharField(max_length=30)),
                ('pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
