# Generated by Django 6.0.1 on 2026-01-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant_store', '0002_product_user_access_level_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='access_req',
            field=models.SmallIntegerField(choices=[(0, 'Стандартный'), (1, 'VIP'), (2, 'Продавец')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.SmallIntegerField(choices=[(0, 'Стандартный'), (1, 'VIP'), (2, 'Продавец')], default=0),
        ),
    ]
