# Generated by Django 6.0.1 on 2026-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant_store', '0003_alter_product_access_req_alter_product_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_recovery_code',
            field=models.SlugField(max_length=6, null=True),
        ),
    ]
