# Generated by Django 6.0.1 on 2026-01-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elephant_store', '0004_user_last_recovery_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('datetime', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephant_store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elephant_store.user')),
            ],
        ),
    ]
